# Gruvbox Dark
# https://github.com/morhetz/gruvbox

[editor]
bg_main      = "#282828"
bg_dark      = "#1d2021"
bg_tab       = "#3c3836"
bg_cursor    = "#32302f"
bg_sel       = "#504945"
bg_select    = "#665c54"
bg_match     = "#3c3836"
fg           = "#ebdbb2"
fg_dim       = "#928374"
divider      = "#3c3836"
guide        = "#3c3836"
guide_active = "#665c54"

[scrollbar]
track = "#282828"
thumb = "#504945"

[statusbar]
branch_bg = "#d65d0e"
lsp_bg    = "#b16286"
file_bg   = "#1d2021"
fg        = "#fbf1c7"
fg_dim    = "#a89984"
powerline = ""

[popup]
bg       = "#3c3836"
border   = "#504945"
hover    = "#504945"
hover_fg = "#fbf1c7"
link     = "#83a598"

[syntax]
keyword  = "#fb4934"
string   = "#b8bb26"
comment  = "#928374"
number   = "#d3869b"
function = "#fabd2f"
type_    = "#8ec07c"
constant = "#d3869b"
variable = "#ebdbb2"
property = "#83a598"
operator = "#fe8019"
default  = "#ebdbb2"

[git]
added     = "#b8bb26"
modified  = "#fabd2f"
deleted   = "#fb4934"
renamed   = "#83a598"
untracked = "#b8bb26"
conflict  = "#fb4934"
ignored   = "#928374"

[diagnostics]
error      = "#fb4934"
warning    = "#fabd2f"
info       = "#83a598"
error_bg   = "#7d2b1e"
warning_bg = "#7d6020"

[finder]
accent          = "#fabd2f"
sel_bg          = "#504945"
match_bg        = "#3c3836"
match_fg        = "#fabd2f"
row_alt_bg      = "#32302f"
title_fg        = "#a89984"
input_sel_bg    = "#665c54"
title_query_fg  = "#d79921"
error_fg        = "#fb4934"
text_dim        = "#7c6f64"
file_dim        = "#d5c4a1"
lnum_sel        = "#fabd2f"
sep_sel         = "#7d6020"
sep_dim         = "#3c3836"
text_sel        = "#ebdbb2"
file_sel        = "#fe8019"
file_sel_dim    = "#7c6f64"

[breadcrumb]
type_color     = "#8ec07c"
function_color = "#fabd2f"
field_color    = "#83a598"
variable_color = "#a89984"
constant_color = "#d3869b"

[tabs]
modified_dot = "#fabd2f"
active_fg    = "#fbf1c7"

[explorer]
folder = "#a89984"
